###  Fully Connected Layer (Feedforward+Backprop)


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X=np.array([[1, 2], [4, 5], [12, 7], [16, 10], [20, 5], [5, 8]  ])
y=np.array([[0,1], [0,1], [1,0], [1,0],  [0,1], [1,0] ])

In [3]:
print(X)

[[ 1  2]
 [ 4  5]
 [12  7]
 [16 10]
 [20  5]
 [ 5  8]]


In [4]:
X.shape

(6, 2)

In [5]:
b=np.array([0.5, 0.6])
w=np.array([ [0.1,0.2], [0.3,0.4] ])

<b>Softmax</b>
$$Let, a=[a_0, a_1, a_2, ..]$$
$$S_i=\frac{e^{a_i}}{\sum_{k=0}^{N} {e^{a_k}}}$$

<b>Task 1: calculate feedforward output</b><br><br>
$\hat{y}=softmax(X.w+b)$

Output should look like the following. <br>

[[0.401 0.599] <br>
 [0.269 0.731] <br>
 [0.119 0.881] <br>
 [0.063 0.937] <br>
 [0.069 0.931] <br>
 [0.198 0.802]]

In [79]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

def calcSoftmax(x):
    y=[]
    for i in range(len(x)):
        m = np.dot(x[i],w)
        z = m + b
        yp = softmax(z)
        y.append(yp)
    return y
yp=calcSoftmax(X)
print(yp)

[array([0.40131234, 0.59868766]), array([0.26894142, 0.73105858]), array([0.11920292, 0.88079708]), array([0.06297336, 0.93702664]), array([0.06913842, 0.93086158]), array([0.19781611, 0.80218389])]


<b>Task 2: calculate log loss</b><br><br> 
$$L_i = - y_i* \sum \log (A_i)$$
\begin{equation*}
L =\frac{1}{N} \sum_i L_i 
\end{equation*}

Output should look like the following. <br>
Loss: [0.513 0.313 2.127 2.765 0.072 1.62 ] <br>
average loss: 1.2351

In [104]:
#your code goes here.

def calcLoss():
    loss =[]
    LI = 0
    for i in range(len(y)):
        Li = -(y[i])*(np.log(yp[i]))
        loss.append(Li)
    #print(LI/len(X))
    return loss
loss = calcLoss()
print(loss)

[array([-0.        ,  0.51301525]), array([-0.        ,  0.31326169]), array([ 2.12692801, -0.        ]), array([ 2.76504356, -0.        ]), array([-0.        ,  0.07164469]), array([ 1.62041741, -0.        ])]


<b>Task 3: calculate gradient</b>

$$dz=\hat{y}-y$$ 
$$dw=\frac{1}{N} ( X^T.dz )$$   
$$db=\frac{1}{N} \sum dz $$ 

Dimension check: y-yh= (2xN).(NX2)=(2x2) 

dw should look like below, <br>
[[-4.452,  4.452], <br>
[-3.243,  3.243]])

db should look like below<br>
[[-0.313,  0.313]]

In [120]:
#your code goes here.
dz = yp-y

dw = (1/len(X))*np.dot(X.T,dz)

print(dw)

[[-4.45217737  4.45217737]
 [-3.2433822   3.2433822 ]]
