### Hopfield


In [1]:
import numpy as np
import matplotlib.pyplot as plt

<b>Let's train 3 pattern. Each pattern has length of four</b>

In [2]:
#initialize w
n=4
w=np.zeros((n,n))
print(w)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#patterns to train.
x1=np.array([1,1,-1,-1])
x2=np.array([-1,1,1,-1])
x3=np.array([1,-1,-1,1])

In [11]:
#make 1x4 vector form
x1=x1.reshape(1,-1)
x2=x2.reshape(1,-1)
x3=x3.reshape(1,-1)

In [12]:
print('x1 shape:',x1.shape)
print('x2 shape:',x2.shape)
print('x3 shape:',x3.shape)

x1 shape: (1, 4)
x2 shape: (1, 4)
x3 shape: (1, 4)


### Training pattern


$$ dw=x.x^T -I \space \space \\ where \space \space I =\space identity \space matrix.$$  
$$w=w+dw$$

<b> Task 1:</b><br>
Train x1 and update w.<br>
<b>updated w</b> should look like the following. 

[[ 0.  1. -1. -1.]<br>
 [ 1.  0. -1. -1.]<br>
 [-1. -1.  0.  1.]<br>
 [-1. -1.  1.  0.]]

In [50]:
#your code goes here.
I = np.identity(4)
def train(x,w):
    

    dw = np.dot(x.T,x)-I

    w = w+dw
    return w
w1=train(x1,0)
print(w1)

[[ 0.  1. -1. -1.]
 [ 1.  0. -1. -1.]
 [-1. -1.  0.  1.]
 [-1. -1.  1.  0.]]


<b> Task 2:</b><br>
Now, train x2 and then x3<br>
After training x3, updated <b>w</b> should look like the following<br>
[[ 0. -1. -3.  1.]<br>
 [-1.  0.  1. -3.]<br>
 [-3.  1.  0. -1.]<br>
 [ 1. -3. -1.  0.]]

In [52]:
#your code goes here.
w2 = train(x2,w1)
w3 = train(x3,w2)
print(w3)


[[ 0. -1. -3.  1.]
 [-1.  0.  1. -3.]
 [-3.  1.  0. -1.]
 [ 1. -3. -1.  0.]]


<b>Task 3:</b> Energy
After training x3, calculate energy.<br>
Output should be = -10

neurons are so interconnected, that they may cause oscillation, or instability. This is called the “energy” of a hopfield net.


$$E=\frac{−1}{2} \sum_{j=1}^n  \sum_{i=1}^n w_{ij}x_i x_j$$

In terms of linear algebra, simpler version is 
$$E = -\frac{1}{2} x^T.W.x$$

In [68]:
#your code goes here.
w = w3
W = np.dot(x3,w)
E = (-1/2)*np.dot(W,x3.T)
print(E)

[[-10.]]
